config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/', to: 'welcome#home', as: 'home' 
  
  # - create 
  #   - new // refers method in controller
  #     - renders // get request
  #   - create // method
  #     - redirect // post request
  # - read
  #   - index // method
  #     - render // get request
  #   - show // method
  #     - render // get request
  # - update
  #   - edit // method
  #     - render // get request
  #   - update // method
  #     - redirect // patch request
  # - delete
  #   - destroy(maybe delete) // method
  #     - redirect // delete request

  resources :posts do
    resources :comments, only:[ :create, :destroy, :edit, :update ]
  end
  # # PATHS
  # index  - products_path
  # new    - new_product_path
  # edit   - edit_product_path
  # show   - product_path
  # create - n/a
  # update - n/a
  # destroy - n/a

  resources :users, only:[:new, :create]
  get '/user/edit', to: 'users#edit', as: 'edit_user'
  patch '/user', to: 'users#update', as: 'update_user'
  get '/user/password', to: 'users#password_edit', as: 'edit_password'
  patch '/user/password', to: 'users#password_update', as: 'update_password'

  # resources :sessions, only:[:new, :create, :destroy]
  get '/session', to: 'sessions#new', as: 'new_session'
  post '/session', to: 'sessions#create'
  delete '/session', to: 'sessions#destroy'
  # Only changed from resources due to wording of homework assignment 
  # requestiong url to be '/session' instead of '/sessions'.

end

app/models/user.rb
class User < ApplicationRecord
 
  has_secure_password
  has_many :posts
  has_many :comments

  REGEX_EMAIL = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :name, 
      presence: { message: 'Must include a name' }, 
      length: { minimum: 3 }
  validates :email, 
      presence: { message: 'Must be a valid email' }, 
      uniqueness: true,
      length: { minimum: 6 }, 
      format: REGEX_EMAIL
  validates :password_digest, 
      presence: true



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
  
    if @user.save
      session[:user_id]= @user.id
      redirect_to home_path, notice: 'Logged in!'
    else
      p @user.errors.full_messages
      render :new
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update user_params
      redirect_to home_path(@user), notice: 'User Updated'
    else
      render :edit, alert: 'Failed to update'
    end
  end

  def password_edit
    @user = current_user
    render :password
  end

  def password_update
    @user = current_user 
    p '*** line 39 ***'

    if @user.authenticate(params[:user][:current_password])
      p '*** line 42 ***'
      if password_confirm?
        p '*** line 44 ***'
        if @user.update password_params
          p '*** line 46 ***'
          redirect_to home_path, notice: 'Password Changed'
        else
          p '*** line 49 ***'
          render :password, alert: 'Failed to change password'
        end
      else
        p '*** line 53 ***'
        render :password, alert: 'New password typed incorrect'
      end
    else 
      p '*** line 57 ***'
      render :password, alert: 'Incorrect Password'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end

  def password_confirm?
    p '*** line 74 ***'
    newPass = params[:user][:password] === params[:user][:password_confirmation]
    oldPass = params[:user][:password] != params[:user][:current_password]
    newPass === true && oldPass === true
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with model: @user, url: update_user_path, method: :patch, local: true do |f| %>
  <% if @user.errors.full_messages.each do |msg| %>
    <ul>
        <li><%= msg %></li>
    </ul>
  <% end; end %>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <% if !user_signed_in? %>
    <div>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>

    <div>
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>
    <%= f.submit 'Sign Up', class: "btn btn-secondary" %>
  <% else %>
    <%= f.submit 'Edit User', class: "btn btn-secondary" %>
  <% end %>

<% end %>



  

app/views/users/edit.html.erb
<%= render 'form' %>

<%= link_to 'Change Password', edit_password_path, class: "btn btn-secondary" %>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/password.html.erb
<%= form_with model: @user, url: update_password_path, method: :patch, local: true do |f| %>
  <div>
    <%= f.label :current_password %>
    <%= f.password_field :current_password %>
  </div>
  <div>
    <%= f.label :password, 'New Password' %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation, 'New Password Confirmation' %>
    <%= f.password_field :password_confirmation %>
  </div>
  <%= f.submit 'Change Password', class: "btn btn-secondary" %>
<% end %>